"""Inference layer tests.

Two angles:
  * :class:`InferenceService` end-to-end on a real (small) checkpoint trained
    in earlier stages — guards against accidental schema drift in the
    suggestion payload.
  * FastAPI app wiring via :func:`fastapi.testclient.TestClient` against an
    in-process stub service — verifies multipart parsing, error mapping, and
    the variations route without booting uvicorn.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest
import torch
from fastapi.testclient import TestClient
from PIL import Image

from fractalov_ml.inference import InferenceService, Suggestion, variations_around
from fractalov_ml.serve import build_app


REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKPOINT = REPO_ROOT / "runs" / "best" / "best.pt"
SAMPLE_IMAGE_DIR = REPO_ROOT / "data" / "v1" / "images" / "julia"


def _has_real_assets() -> bool:
    return CHECKPOINT.exists() and SAMPLE_IMAGE_DIR.exists() and any(SAMPLE_IMAGE_DIR.iterdir())


needs_assets = pytest.mark.skipif(
    not _has_real_assets(),
    reason="requires runs/best/best.pt + data/v1 — generated by the Stage 6 workflow",
)


# ----------------------------------------------------------------- InferenceService


@needs_assets
def test_inference_service_predicts_julia_on_julia_sample() -> None:
    svc = InferenceService(CHECKPOINT, device_override="cpu")
    sample = sorted(SAMPLE_IMAGE_DIR.iterdir())[0]
    suggestion = svc.predict_recipe(sample.read_bytes())

    assert suggestion.family == "julia"
    assert 0.0 <= suggestion.family_confidence <= 1.0
    assert sum(suggestion.family_distribution.values()) == pytest.approx(1.0, abs=1e-3)

    recipe = suggestion.recipe
    assert recipe["fractalType"] == "julia"
    assert "cRe" in recipe["params"] and "cIm" in recipe["params"]
    assert -1.5 - 1e-6 <= recipe["params"]["cRe"] <= 1.5 + 1e-6


def test_variations_around_jitters_within_documented_bounds() -> None:
    base = {
        "viewport": {"xMin": -1.5, "xMax": 1.5, "yMin": -1.5, "yMax": 1.5},
        "renderSettings": {"widthPx": 256, "heightPx": 256, "samplesPerAxis": 1},
        "colorSettings": {"paletteName": "fire", "mode": "linear"},
        "fractalType": "julia",
        "params": {
            "cRe": -0.7,
            "cIm": 0.27,
            "maxIter": 200,
            "escapeRadius": 2.0,
            "smoothing": True,
        },
    }
    variants = variations_around(base, count=8, seed=7)
    assert len(variants) == 8
    for v in variants:
        # zoom factor in [0.6, 1.4] ⇒ span scales accordingly
        span = v["viewport"]["xMax"] - v["viewport"]["xMin"]
        assert 0.6 * 3.0 - 1e-6 <= span <= 1.4 * 3.0 + 1e-6
        # max_iter scales by [0.75, 1.25] ⇒ at least 50, at most ~250
        assert 50 <= v["params"]["maxIter"] <= 260
        # cRe / cIm jitter ±0.05
        assert abs(v["params"]["cRe"] - base["params"]["cRe"]) <= 0.06
        assert abs(v["params"]["cIm"] - base["params"]["cIm"]) <= 0.06


def test_variations_seed_is_reproducible() -> None:
    base = {
        "viewport": {"xMin": -2.0, "xMax": 1.0, "yMin": -1.2, "yMax": 1.2},
        "renderSettings": {"widthPx": 256, "heightPx": 256, "samplesPerAxis": 1},
        "colorSettings": {"paletteName": "fire", "mode": "linear"},
        "fractalType": "mandelbrot",
        "params": {"maxIter": 200, "escapeRadius": 2.0, "smoothing": True},
    }
    a = variations_around(base, count=4, seed=11)
    b = variations_around(base, count=4, seed=11)
    assert a == b


# ----------------------------------------------------------------- FastAPI app


class StubService:
    """Lightweight stand-in for InferenceService used by :func:`build_app`.
    Exposes only the attributes the router touches."""

    def __init__(self) -> None:
        self.checkpoint = Path("/stub/best.pt")
        self.device = torch.device("cpu")
        self.base_channels = 16

    def predict_recipe(self, image_bytes: bytes, **kwargs) -> Suggestion:
        Image.open(io.BytesIO(image_bytes)).verify()  # ensure it's a real image
        return Suggestion(
            family="julia",
            family_confidence=0.99,
            family_distribution={
                "burning_ship": 0.005,
                "julia": 0.99,
                "mandelbrot": 0.003,
                "multibrot": 0.002,
            },
            c_re=-0.7,
            c_im=0.27,
            recipe={
                "viewport": {"xMin": -1.5, "xMax": 1.5, "yMin": -1.5, "yMax": 1.5},
                "renderSettings": {"widthPx": 512, "heightPx": 512, "samplesPerAxis": 1},
                "colorSettings": {"paletteName": "fire", "mode": "linear"},
                "fractalType": "julia",
                "params": {
                    "cRe": -0.7,
                    "cIm": 0.27,
                    "maxIter": 200,
                    "escapeRadius": 2.0,
                    "smoothing": True,
                },
            },
        )


@pytest.fixture
def stub_app() -> TestClient:
    return TestClient(build_app(StubService()))


def _png_bytes(width: int = 32, height: int = 32) -> bytes:
    img = Image.new("RGB", (width, height), color=(120, 80, 200))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def test_healthz_returns_metadata(stub_app: TestClient) -> None:
    resp = stub_app.get("/healthz")
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "ok"
    assert body["base_channels"] == 16


def test_suggest_from_image_round_trip(stub_app: TestClient) -> None:
    resp = stub_app.post(
        "/infer/suggest-from-image",
        files={"file": ("input.png", _png_bytes(), "image/png")},
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["family"] == "julia"
    assert body["recipe"]["fractalType"] == "julia"
    assert body["c_re"] == pytest.approx(-0.7)


def test_suggest_from_image_rejects_non_image(stub_app: TestClient) -> None:
    resp = stub_app.post(
        "/infer/suggest-from-image",
        files={"file": ("note.txt", b"not an image", "text/plain")},
    )
    assert resp.status_code == 415


def test_variations_endpoint(stub_app: TestClient) -> None:
    body = {
        "recipe": {
            "viewport": {"xMin": -1.5, "xMax": 1.5, "yMin": -1.5, "yMax": 1.5},
            "renderSettings": {"widthPx": 256, "heightPx": 256, "samplesPerAxis": 1},
            "colorSettings": {"paletteName": "fire", "mode": "linear"},
            "fractalType": "julia",
            "params": {
                "cRe": -0.7,
                "cIm": 0.27,
                "maxIter": 200,
                "escapeRadius": 2.0,
                "smoothing": True,
            },
        },
        "count": 4,
        "seed": 1,
    }
    resp = stub_app.post("/infer/variations", json=body)
    assert resp.status_code == 200
    recipes = resp.json()["recipes"]
    assert len(recipes) == 4
    for r in recipes:
        assert r["fractalType"] == "julia"


def test_variations_rejects_malformed_recipe(stub_app: TestClient) -> None:
    resp = stub_app.post("/infer/variations", json={"recipe": {}, "count": 2, "seed": 0})
    assert resp.status_code == 400
